name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build7:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run build
        run: build7.bat
        shell: cmd

      - name: run installer build
        run: installer/build7.bat
        shell: cmd

      - name: upload installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer-artifacts
          path: installer/dist/**
          retention-days: 7

      - name: create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: installer/dist/*.msi
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
